branches:
  only:
    - develop
    - release
    - feature/travis
services:
  - docker
before_install:
  - cd examples/todomvc
  - docker-compose build
  - docker-compose up -d
script:
  - docker-compose run nightwatch bash -c "npm test"
notifications:
  slack: zackferrofields:XNoCn4AKv4YLQJIdElyOQTyg
