language: node_js
env:
  DOCKER_TAG: monocle-todo
branches:
  only:
    - release
services:
  - docker
before_install:
  - cd examples/todomvc
  - docker-compose up -d
install:
  - npm i nightwatch cucumber nightwatch-cucumber
script:
  - npm run test:features
