branches:
  only:
    - develop
    - release
    - feature/travis
services:
  - docker
before_install:
  - cd examples/todomvc
  - docker-compose up -d
install:
  - npm i nightwatch cucumber nightwatch-cucumber
script:
  - npm run test:features
notifications:
  slack: zackferrofields:XNoCn4AKv4YLQJIdElyOQTyg
